export enum profileActionTypes {
    FETCH_PROFILE = 'FETCH_PROFILE',
    FETCH_PROFILE_NONE = 'FETCH_PROFILE_NONE',
    FETCH_PROFILE_SUCCESS =  'FETCH_PROFILE_SUCCESS',
    FETCH_PROFILE_ERROR = 'FETCH_PROFILE_ERROR'
}

export enum orgsActionTypes {
    FETCH_ORGS = 'FETCH_ORGS',
    FETCH_ORGS_NONE = 'INITIAL_RENDER_ORGS',
    FETCH_ORGS_SUCCESS =  'FETCH_ORGS_SUCCESS',
    FETCH_ORGS_ERROR = 'FETCH_ORGS_ERROR'
}

export enum narrativeActionTypes {
    FETCH_NARRATIVE = 'FETCH_NARRATIVE',
    FETCH_NARRATIVE_NONE = 'INITIAL_RENDER_NARRATIVE',
    FETCH_NARRATIVE_SUCCESS =  'FETCH_NARRATIVE_SUCCESS',
    FETCH_NARRATIVE_ERROR = 'FETCH_NARRATIVE_ERROR'
}