export enum profileActionTypes {
    FETCH_PROFILE = 'FETCH_PROFILE',
    INITIAL_RENDER_PROFILE = 'INITIAL_RENDER_PROFILE',
    FETCH_PROFILE_SUCCESS =  'FETCH_PROFILE_SUCCESS',
    FETCH_PROFILE_ERROR = 'FETCH_PROFILE_ERROR'
}

export enum orgsActionTypes {
    LOAD_ORGS = 'LOAD_ORGS',
    FETCH_ORGS = 'FETCH_ORGS',
    INITIAL_RENDER_ORGS = 'INITIAL_RENDER_ORGS',
    FETCH_ORGS_SUCCESS =  'FETCH_ORGS_SUCCESS',
    FETCH_ORGS_ERROR = 'FETCH_ORGS_ERROR'
}